create table if not exists public.user_roles (
  user_id uuid primary key references auth.users (id) on delete cascade,
  role text not null check (role = 'developer'),
  created_at timestamptz not null default now()
);

create table if not exists public.voc_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  user_email text not null,
  category text not null check (category in ('改善要望', '不具合', '質問', 'その他')),
  subject text not null check (char_length(subject) between 1 and 120),
  message text not null check (char_length(message) between 1 and 4000),
  status text not null default '未対応' check (status in ('未対応', '対応中', '対応済み')),
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists voc_messages_inbox_idx
  on public.voc_messages (archived_at, created_at desc);
create index if not exists voc_messages_user_idx
  on public.voc_messages (user_id, created_at desc);

alter table public.user_roles enable row level security;
alter table public.voc_messages enable row level security;

revoke all on public.user_roles from anon, authenticated;
revoke all on public.voc_messages from anon, authenticated;
grant select, insert, update, delete on public.voc_messages to authenticated;
grant usage, select on sequence public.voc_messages_id_seq to authenticated;

create or replace function public.is_current_user_developer()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.user_roles
    where user_id = auth.uid()
      and role = 'developer'
  );
$$;

revoke all on function public.is_current_user_developer() from public, anon;
grant execute on function public.is_current_user_developer() to authenticated;

create or replace function public.set_voc_identity()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  new.user_id := auth.uid();
  select email into new.user_email
  from auth.users
  where id = auth.uid();

  if new.user_email is null then
    raise exception 'Authenticated email is required';
  end if;

  new.status := '未対応';
  new.archived_at := null;
  new.created_at := now();
  new.updated_at := now();
  return new;
end;
$$;

revoke all on function public.set_voc_identity() from public, anon, authenticated;

drop trigger if exists set_voc_identity_before_insert on public.voc_messages;
create trigger set_voc_identity_before_insert
  before insert on public.voc_messages
  for each row execute function public.set_voc_identity();

create or replace function public.set_voc_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

revoke all on function public.set_voc_updated_at() from public, anon, authenticated;

drop trigger if exists set_voc_updated_at_before_update on public.voc_messages;
create trigger set_voc_updated_at_before_update
  before update on public.voc_messages
  for each row execute function public.set_voc_updated_at();

drop policy if exists voc_messages_read_own_or_developer on public.voc_messages;
create policy voc_messages_read_own_or_developer
  on public.voc_messages for select to authenticated
  using (user_id = auth.uid() or public.is_current_user_developer());

drop policy if exists voc_messages_insert_own on public.voc_messages;
create policy voc_messages_insert_own
  on public.voc_messages for insert to authenticated
  with check (user_id = auth.uid());

drop policy if exists voc_messages_update_developer on public.voc_messages;
create policy voc_messages_update_developer
  on public.voc_messages for update to authenticated
  using (public.is_current_user_developer())
  with check (public.is_current_user_developer());

drop policy if exists voc_messages_delete_developer on public.voc_messages;
create policy voc_messages_delete_developer
  on public.voc_messages for delete to authenticated
  using (public.is_current_user_developer());

create or replace function public.delete_my_account()
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  account_id uuid := auth.uid();
begin
  if account_id is null then
    raise exception 'Authentication required';
  end if;

  delete from auth.users where id = account_id;
end;
$$;

revoke all on function public.delete_my_account() from public, anon;
grant execute on function public.delete_my_account() to authenticated;